### ISSUE TITLE
Rules Engine Errors with Successful Rule

### ISSUE THREAD

**Issue by bishopbm1** [StackStorm/st2#4934]
## SUMMARY

Errors are generated in `/var/log/st2/st2rulesengine.log` even though the rule is run successfully with out issues. 

### STACKSTORM VERSION

```
# st2 --version
st2 3.2.0, on Python 2.7.5
```

##### OS, environment, install method

```
# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.8 (Maipo)
```

Installed with Puppet module

## Steps to reproduce the problem

Reproduce issue with any Rule but was able to reproduce with the below rule definition taken from: https://github.com/StackStorm/st2/blob/master/contrib/examples/rules/sample_rule_with_timer.yaml
```
---
name: sample_rule_with_timer
pack: "examples"
description: Sample rule using an Interval Timer.
enabled: true

trigger:
  parameters:
    delta: 5
    unit: seconds
  type: core.st2.IntervalTimer

criteria: {}

action:
  parameters:
    cmd: echo "{{trigger.executed_at}}"
  ref: core.local
```

## Expected Results

I expect that the rule is run successfully with 0 errors.

## Actual Results

Even though the execution is successful errors are generated in the `/var/log/st2/st2rulesengine.log`
```
2020-05-04 14:18:49,473 140709056184880 INFO engine [-] Found 1 rules defined for trigger core.38d1bbdd-a659-4038-b3f4-ce250eb79db8
2020-05-04 14:18:49,475 140709056184880 ERROR traceback [-] Traceback (most recent call last):

2020-05-04 14:18:49,476 140709056184880 ERROR traceback [-]   File "/usr/lib64/python2.7/logging/__init__.py", line 851, in emit

2020-05-04 14:18:49,476 140709056184880 ERROR traceback [-]     msg = self.format(record)

2020-05-04 14:18:49,477 140709056184880 ERROR traceback [-]   File "/usr/lib64/python2.7/logging/__init__.py", line 724, in format

2020-05-04 14:18:49,477 140709056184880 ERROR traceback [-]     return fmt.format(record)

2020-05-04 14:18:49,478 140709056184880 ERROR traceback [-]   File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/logging/formatters.py", line 176, in format

2020-05-04 14:18:49,478 140709056184880 ERROR traceback [-]     attributes = self._format_extra_attributes(attributes=attributes)

2020-05-04 14:18:49,479 140709056184880 ERROR traceback [-]   File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/logging/formatters.py", line 151, in _format_extra_attributes

2020-05-04 14:18:49,480 140709056184880 ERROR traceback [-]     value = serialize_object(obj=value)

2020-05-04 14:18:49,480 140709056184880 ERROR traceback [-]   File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/logging/formatters.py", line 65, in serialize_object

2020-05-04 14:18:49,481 140709056184880 ERROR traceback [-]     value = obj.to_serializable_dict(mask_secrets=True)

2020-05-04 14:18:49,481 140709056184880 ERROR traceback [-]   File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/models/db/stormbase.py", line 105, in to_serializable_dict

2020-05-04 14:18:49,482 140709056184880 ERROR traceback [-]     serializable_dict = self.mask_secrets(value=serializable_dict)

2020-05-04 14:18:49,482 140709056184880 ERROR traceback [-]   File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/models/db/rule.py", line 122, in mask_secrets

2020-05-04 14:18:49,483 140709056184880 ERROR traceback [-]     action_ref = result.get('action', {}).get('ref', None)

2020-05-04 14:18:49,484 140709056184880 ERROR traceback [-] AttributeError: 'str' object has no attribute 'get'

2020-05-04 14:18:49,484 140709056184880 ERROR filter [-] Logged from file filter.py, line 72

2020-05-04 14:18:49,486 140709056184880 ERROR traceback [-] Traceback (most recent call last):

2020-05-04 14:18:49,487 140709056184880 ERROR traceback [-]   File "/usr/lib64/python2.7/logging/__init__.py", line 851, in emit

2020-05-04 14:18:49,488 140709056184880 ERROR traceback [-]     msg = self.format(record)

2020-05-04 14:18:49,488 140709056184880 ERROR traceback [-]   File "/usr/lib64/python2.7/logging/__init__.py", line 724, in format

2020-05-04 14:18:49,489 140709056184880 ERROR traceback [-]     return fmt.format(record)

2020-05-04 14:18:49,489 140709056184880 ERROR traceback [-]   File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/logging/formatters.py", line 176, in format

2020-05-04 14:18:49,490 140709056184880 ERROR traceback [-]     attributes = self._format_extra_attributes(attributes=attributes)

2020-05-04 14:18:49,490 140709056184880 ERROR traceback [-]   File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/logging/formatters.py", line 151, in _format_extra_attributes

2020-05-04 14:18:49,491 140709056184880 ERROR traceback [-]     value = serialize_object(obj=value)

2020-05-04 14:18:49,491 140709056184880 ERROR traceback [-]   File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/logging/formatters.py", line 65, in serialize_object

2020-05-04 14:18:49,492 140709056184880 ERROR traceback [-]     value = obj.to_serializable_dict(mask_secrets=True)

2020-05-04 14:18:49,493 140709056184880 ERROR traceback [-]   File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/models/db/stormbase.py", line 105, in to_serializable_dict

2020-05-04 14:18:49,493 140709056184880 ERROR traceback [-]     serializable_dict = self.mask_secrets(value=serializable_dict)

2020-05-04 14:18:49,494 140709056184880 ERROR traceback [-]   File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/models/db/rule.py", line 122, in mask_secrets

2020-05-04 14:18:49,494 140709056184880 ERROR traceback [-]     action_ref = result.get('action', {}).get('ref', None)

2020-05-04 14:18:49,495 140709056184880 ERROR traceback [-] AttributeError: 'str' object has no attribute 'get'

2020-05-04 14:18:49,495 140709056184880 ERROR handlers [-] Logged from file filter.py, line 72

2020-05-04 14:18:49,497 140709056184880 ERROR traceback [-] Traceback (most recent call last):

2020-05-04 14:18:49,498 140709056184880 ERROR traceback [-]   File "/usr/lib64/python2.7/logging/__init__.py", line 851, in emit

2020-05-04 14:18:49,499 140709056184880 ERROR traceback [-]     msg = self.format(record)

2020-05-04 14:18:49,499 140709056184880 ERROR traceback [-]   File "/usr/lib64/python2.7/logging/__init__.py", line 724, in format

2020-05-04 14:18:49,500 140709056184880 ERROR traceback [-]     return fmt.format(record)

2020-05-04 14:18:49,500 140709056184880 ERROR traceback [-]   File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/logging/formatters.py", line 241, in format

2020-05-04 14:18:49,501 140709056184880 ERROR traceback [-]     attributes = self._format_extra_attributes(attributes=attributes)

2020-05-04 14:18:49,501 140709056184880 ERROR traceback [-]   File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/logging/formatters.py", line 151, in _format_extra_attributes

2020-05-04 14:18:49,502 140709056184880 ERROR traceback [-]     value = serialize_object(obj=value)

2020-05-04 14:18:49,503 140709056184880 ERROR traceback [-]   File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/logging/formatters.py", line 65, in serialize_object

2020-05-04 14:18:49,503 140709056184880 ERROR traceback [-]     value = obj.to_serializable_dict(mask_secrets=True)

2020-05-04 14:18:49,504 140709056184880 ERROR traceback [-]   File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/models/db/stormbase.py", line 105, in to_serializable_dict

2020-05-04 14:18:49,504 140709056184880 ERROR traceback [-]     serializable_dict = self.mask_secrets(value=serializable_dict)

2020-05-04 14:18:49,505 140709056184880 ERROR traceback [-]   File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/models/db/rule.py", line 122, in mask_secrets

2020-05-04 14:18:49,505 140709056184880 ERROR traceback [-]     action_ref = result.get('action', {}).get('ref', None)

2020-05-04 14:18:49,506 140709056184880 ERROR traceback [-] AttributeError: 'str' object has no attribute 'get'

2020-05-04 14:18:49,506 140709056184880 ERROR handlers [-] Logged from file filter.py, line 72

2020-05-04 14:18:49,508 140709056184880 INFO matcher [-] 1 rule(s) found to enforce for 38d1bbdd-a659-4038-b3f4-ce250eb79db8.
2020-05-04 14:18:49,508 140709056184880 INFO engine [-] Matched 1 rule(s) for trigger_instance 5eb05c896077d5bca5610507 (trigger=core.38d1bbdd-a659-4038-b3f4-ce250eb79db8)
2020-05-04 14:18:49,524 140709056184880 INFO enforcer [-] Invoking action core.local for trigger_instance 5eb05c896077d5bca5610507 with params {"cmd": "echo \"{{trigger.executed_at}}\""}.
2020-05-04 14:18:49,739 140709056184880 ERROR traceback [-] Traceback (most recent call last):

2020-05-04 14:18:49,740 140709056184880 ERROR traceback [-]   File "/usr/lib64/python2.7/logging/__init__.py", line 851, in emit

2020-05-04 14:18:49,740 140709056184880 ERROR traceback [-]     msg = self.format(record)

2020-05-04 14:18:49,741 140709056184880 ERROR traceback [-]   File "/usr/lib64/python2.7/logging/__init__.py", line 724, in format

2020-05-04 14:18:49,741 140709056184880 ERROR traceback [-]     return fmt.format(record)

2020-05-04 14:18:49,742 140709056184880 ERROR traceback [-]   File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/logging/formatters.py", line 241, in format

2020-05-04 14:18:49,743 140709056184880 ERROR traceback [-]     attributes = self._format_extra_attributes(attributes=attributes)

2020-05-04 14:18:49,743 140709056184880 ERROR traceback [-]   File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/logging/formatters.py", line 151, in _format_extra_attributes

2020-05-04 14:18:49,744 140709056184880 ERROR traceback [-]     value = serialize_object(obj=value)

2020-05-04 14:18:49,744 140709056184880 ERROR traceback [-]   File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/logging/formatters.py", line 65, in serialize_object

2020-05-04 14:18:49,745 140709056184880 ERROR traceback [-]     value = obj.to_serializable_dict(mask_secrets=True)

2020-05-04 14:18:49,745 140709056184880 ERROR traceback [-]   File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/models/db/stormbase.py", line 105, in to_serializable_dict

2020-05-04 14:18:49,746 140709056184880 ERROR traceback [-]     serializable_dict = self.mask_secrets(value=serializable_dict)

2020-05-04 14:18:49,748 140709056184880 ERROR traceback [-]   File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/models/db/rule.py", line 122, in mask_secrets

2020-05-04 14:18:49,748 140709056184880 ERROR traceback [-]     action_ref = result.get('action', {}).get('ref', None)

2020-05-04 14:18:49,749 140709056184880 ERROR traceback [-] AttributeError: 'str' object has no attribute 'get'

2020-05-04 14:18:49,750 140709056184880 ERROR handlers [-] Logged from file enforcer.py, line 118

2020-05-04 14:18:50,419 140709057006000 INFO engine [-] Found 0 rules defined for trigger core.st2.generic.actiontrigger
2020-05-04 14:18:50,424 140709057006000 INFO engine [-] No matching rules found for trigger instance 5eb05c8a6077d5bca561050c.
```

**Comment by nmaludy** [comment]
Potential offending commit: https://github.com/StackStorm/st2/commit/bf421a304cc7a410693d5ae90203cf8f97c27510#diff-e71bead32ed3f0c916cddf4b2f26110f

**Comment by bishopbm1** [comment]
PR for fix: https://github.com/StackStorm/st2/pull/4941
