### ISSUE TITLE
Attempting to use auth on the API when it's disabled results in nasty errors

### ISSUE THREAD

**Issue by agaffney** [StackStorm/st2#2498]
I ran into this while trying to get Hubot working with Stackstorm (1.3.x and 1.4dev). Even though auth was working/required on the web frontend, it was disabled via st2.conf. When Hubot would auth and then try to use the API, it would get a HTTP 500 error.

For a request such as this (via nginx):

```
172.17.0.36 - - [12/Feb/2016:16:45:20 -0800] "GET /api/v1/stream?x-auth-token=9e1fdd874bf04c0ba0789ced62f51d97 HTTP/1.1" 500 46 "-" "-"
```

You'd see this in `st2api.log`:

```
2016-02-12 16:38:30,273 139669775957680 INFO log [-] args = (<st2api.controllers.v1.stream.StreamController object at 0x7f07676337d0>,)
2016-02-12 16:38:30,273 139669775957680 INFO log [-] kwargs = {u'x-auth-token': u'e7abfd1066e543f585ab877191043a5a'}
2016-02-12 16:38:30,274 139669775957680 ERROR log [-] API call failed: get_all() got an unexpected keyword argument 'x-auth-token'
Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/pecan/core.py", line 631, in __call__
    self.invoke_controller(controller, args, kwargs, state)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/pecan/core.py", line 531, in invoke_controller
    result = controller(*args, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/models/api/base.py", line 245, in callfunction
    raise e
TypeError: get_all() got an unexpected keyword argument 'x-auth-token' (_exception_data={},_exception_class='TypeError',_exception_message="get_all() got an unexpected keyword argument 'x-auth-token'")
2016-02-12 16:38:30,275 139669775957680 ERROR log [-] Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/pecan/core.py", line 631, in __call__
    self.invoke_controller(controller, args, kwargs, state)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/pecan/core.py", line 531, in invoke_controller
    result = controller(*args, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/models/api/base.py", line 245, in callfunction
    raise e
TypeError: get_all() got an unexpected keyword argument 'x-auth-token'
Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/pecan/core.py", line 631, in __call__
    self.invoke_controller(controller, args, kwargs, state)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/pecan/core.py", line 531, in invoke_controller
    result = controller(*args, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/models/api/base.py", line 245, in callfunction
    raise e
TypeError: get_all() got an unexpected keyword argument 'x-auth-token'
2016-02-12 16:38:30,275 139669775957680 INFO log [-] 7134fb02-4a85-485d-850b-f6f00e0c123c - GET /v1/stream (remote_addr='127.0.0.1',method='GET',status_code='500 Internal Server Error',request_id='7134fb02-4a85-485d-850b-f6f00e0c123c',path='/v1/stream')
```

Setting `enable = True` under the `auth` section makes everything happy.

**Comment by enykeev** [comment]
It is a known problem and we even have a PR fixing it (see https://github.com/StackStorm/st2/pull/2102), although we were unable to reach an agreement internally on how it should be handled. May be your feedback can tip the scale.

**Comment by agaffney** [comment]
I'm on the fence in that debate, and I don't have strong feelings anyway, since this is no longer affecting me. Personally, I think that it should be done on the server-side (because there can be multiple client implementations, and it's silly to fix it in all of them), but I also agree that there should be *some* feedback to the client that auth is disabled.

**Comment by manasdk** [comment]
500 is bad but definitely the request needs to be rejected.

Allowing a request through when auth is disabled even though the client is passing in a token that is enabled is setting the wrong expectation for a client. Also, I wonder where this token comes from if auth is actually disabled.

**Comment by enykeev** [comment]
Finally fixed in https://github.com/StackStorm/st2/pull/2102.
