### ISSUE TITLE
Sensors have stopped working after upgrade to st2 2.7.1

### ISSUE THREAD

**Issue by harishgopalan** [StackStorm/st2#4094]
Hi Stackstorm Dev Team,

Sensors have stopped working in st2 2.7.1 after upgrade from st2 2.6.0

It was giving the error : module "object" has no attribute "poll" whenever the sensor start to initialize. This error was seen in st2sensorcontainer.log

Even the default linux.FileWatchSensor threw errors during sensor initialization when we bring the st2sensorcontainer service

Kindly please look into this issue

Regards
Harish

**Comment by LindsayHill** [comment]
Something else is going on with that file watch sensor - I suspect something related to pyinotify. I think that's a red herring here.

Testing with a passive sensor - e.g. github.com/StackStorm/githubwebhooksensor, it is running OK. 

@harishgopalan which sensor are you having problems with?

**Comment by harishgopalan** [comment]
Hi Lindsay,

We've a standalone sensor which monitors some failures and dispatches
trigger and then wait for X minute before checking again.

After upgrade to 2.7.1 we noticed that the sensors are not running, when we
looked at the st2sensorcontainer.log, we noticed this error is occurring
across all sensors

Error : module 'object' has no attribute 'poll'

Regards
Harish

**Comment by LindsayHill** [comment]
Can you provide a specific example other than the filewatch sensor? I need to see the actual code

**Comment by schreyack** [comment]
I am seeing the same/similar issue with the git sensor from the exchange:

`2018-05-07 17:48:53,429 139717262429072 INFO manager [-] Sensor git.GitCommitSensor updated. Reloading sensor.
2018-05-07 17:48:53,430 139717262429072 WARNING process_container [-] Sensor git.GitCommitSensor isn't running in this container.
2018-05-07 17:48:53,435 139717262429072 AUDIT access [-] Access granted to "sensors_container" with the token set to expire at "2018-05-08T17:48:53.433561Z". (username='sensors_container',token_expiration='2018-05-08T17:48:53.433561Z')
2018-05-07 17:48:53,435 139717262429072 WARNING api [-] "auth.api_url" configuration option is not configured
2018-05-07 17:48:53,444 139717262429072 INFO manager [-] Sensor git.GitCommitSensor reloaded.
2018-05-07 17:48:54,491 139833116718896 ERROR (unknown file) [-] Traceback (most recent call last):

2018-05-07 17:48:54,492 139833116718896 ERROR (unknown file) [-]   File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2reactor/container/sensor_wrapper.py", line 379, in <module>

2018-05-07 17:48:54,492 139833116718896 ERROR (unknown file) [-]     
2018-05-07 17:48:54,492 139833116718896 ERROR (unknown file) [-] parent_args=parent_args)

2018-05-07 17:48:54,492 139833116718896 ERROR (unknown file) [-]   File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2reactor/container/sensor_wrapper.py", line 228, in __init__

2018-05-07 17:48:54,492 139833116718896 ERROR (unknown file) [-]     
2018-05-07 17:48:54,493 139833116718896 ERROR (unknown file) [-] self._sensor_instance = self._get_sensor_instance()

2018-05-07 17:48:54,493 139833116718896 ERROR (unknown file) [-]   File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2reactor/container/sensor_wrapper.py", line 314, in _get_sensor_instance

2018-05-07 17:48:54,493 139833116718896 ERROR (unknown file) [-]     
2018-05-07 17:48:54,493 139833116718896 ERROR (unknown file) [-] raise exc_cls(msg)

2018-05-07 17:48:54,493 139833116718896 ERROR (unknown file) [-] AttributeError
2018-05-07 17:48:54,493 139833116718896 ERROR (unknown file) [-] : 
2018-05-07 17:48:54,493 139833116718896 ERROR (unknown file) [-] Failed to load sensor class from file "/opt/stackstorm/packs/git/sensors/git_commit_sensor.py" (sensor file most likely doesn't exist or contains invalid syntax): 'module' object has no attribute 'poll'

Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2reactor/container/sensor_wrapper.py", line 307, in _get_sensor_instance
    class_name=self._class_name)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/util/loader.py", line 153, in register_plugin_class
    module = imp.load_source(module_name, file_path)
  File "/opt/stackstorm/packs/git/sensors/git_commit_sensor.py", line 10, in <module>
    from git.repo import Repo
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/git/__init__.py", line 82, in <module>
    refresh()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/git/__init__.py", line 73, in refresh
    if not Git.refresh(path=path):
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/git/cmd.py", line 230, in refresh
    cls().version()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/git/cmd.py", line 551, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/git/cmd.py", line 1010, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/git/cmd.py", line 779, in execute
    stdout_value, stderr_value = proc.communicate()
  File "/usr/lib/python2.7/subprocess.py", line 799, in communicate
    return self._communicate(input)
  File "/usr/lib/python2.7/subprocess.py", line 1401, in _communicate
    stdout, stderr = self._communicate_with_poll(input)
  File "/usr/lib/python2.7/subprocess.py", line 1431, in _communicate_with_poll
    poller = select.poll()
AttributeError: 'module' object has no attribute 'poll'

2018-05-07 17:48:54,493 139833116718896 ERROR (unknown file) [-] 

2018-05-07 17:48:56,797 139717262429232 INFO process_container [-] Process for sensor git.GitCommitSensor has exited with code 1`

**Comment by Kami** [comment]
Thanks for reporting this - I will dig in and look into it tomorrow, I have some idea on what might have gone wrong (likely to eventlet upgrade related).

**Comment by schreyack** [comment]
Thanks for the quick response on this!  By chance is there a timeline/date for 2.7.2 to be released?

**Comment by LindsayHill** [comment]
No fixed date yet, but 'soon'.

You can make those changes in #4118 on your system now if you want to test it out

**Comment by Kami** [comment]
@harishgopalan @schreyack Just a heads up - v2.7.2 with bug fix for this issue is now out and you can upgrade your v2.7.1 installation.

Thanks again for reporting this.

**Comment by schreyack** [comment]
thank you!

**Comment by harishgopalan** [comment]
Thanks a lot, i will revert after testing the new version

**Comment by Sphinxs** [comment]
Is this fixed in ST2 3.1.0?

I have received the error:

```
2019-12-20 14:36:14,293 140463402104944 ERROR (unknown file) [-] Failed to load sensor class from file "/opt/stackstorm/packs/hub/sensors/client_data.py" (sensor file most likely doesn't exist or contains invalid syntax): Directory "/opt/stackstorm/packs/hub/sensors" with plugins doesn't exist

Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2reactor/container/sensor_wrapper.py", line 288, in _get_sensor_instance
    class_name=self._class_name)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/util/loader.py", line 141, in register_plugin_class
    _register_plugin_path(plugin_dir)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/util/loader.py", line 52, in _register_plugin_path
    raise Exception('Directory "%s" with plugins doesn\'t exist' % (plugin_dir_abs_path))
Exception: Directory "/opt/stackstorm/packs/hub/sensors" with plugins doesn't exist

2019-12-20 14:36:14,294 140463402104944 ERROR (unknown file) [-] 
```

When running a similar application to the Flask [example](https://github.com/StackStorm/st2/tree/master/contrib/examples/sensors).
