### ISSUE TITLE
st2 v2.4 custom pack installation console error

### ISSUE THREAD

**Issue by emptywee** [StackStorm/st2#3719]
After upgrade from 2.3 to 2.4 custom pack installation command in console started to blow up with a `'LiveAction' object has no attribute 'id'` error from time to time. Not always, but very often. Pack installation action itself is not affected and is successful in history. Pack is being installed and registered as normal. 

```
st2 --debug pack install git@github.com:[obfuscated]=dev
# -------- begin 139888917251344 request ----------
curl -X POST -H  'Connection: keep-alive' -H  'Accept-Encoding: gzip, deflate' -H  'Accept: */*' -H  'User-Agent: python-requests/2.14.2' -H  'content-type: application/json' -H  'Content-Length: 2' -H  'Authorization: Basic c3ZjLmNwcnRvcHM6R2FqdkdERWpsdnU1V2NTd09kQVk=' --data-binary '{}' https://lvcops101.[obfuscated].com/auth/tokens
# -------- begin 139888917251344 response ----------
{
    "service": false,
    "expiry": "2017-09-06T22:49:59.483030Z",
    "token": "b90f9cefc79540bf9c9c6f9cb1d6743a",
    "user": "[obfuscated]",
    "id": "59af2a17bd00ef184c26b3d9",
    "metadata": {}
}
# -------- end 139888917251344 response ------------

2017-09-05 15:49:59,528  DEBUG - Token has been cached in "/export/home/[obfuscated]/.st2/token-[obfuscated]"
# -------- begin 139888917284112 request ----------
curl -X POST -H  'Connection: keep-alive' -H  'Accept-Encoding: gzip, deflate' -H  'Accept: */*' -H  'User-Agent: python-requests/2.14.2' -H  'content-type: application/json' -H  'X-Auth-Token: b90f9cefc79540bf9c9c6f9cb1d6743a' -H  'Content-Length: 56' --data-binary '{"pack": "git@github.com:[obfuscated].git=dev"}' https://lvcops101.[obfuscated].com/api/v1/packs/index/search
# -------- begin 139888917284112 response ----------
[]
# -------- end 139888917284112 response ------------

# -------- begin 139888917284112 request ----------
curl -X POST -H  'Connection: keep-alive' -H  'Accept-Encoding: gzip, deflate' -H  'Accept: */*' -H  'User-Agent: python-requests/2.14.2' -H  'content-type: application/json' -H  'X-Auth-Token: b90f9cefc79540bf9c9c6f9cb1d6743a' -H  'Content-Length: 75' --data-binary '{"force": false, "packs": ["git@github.com:[obfuscated].git=dev"]}' https://lvcops101.[obfuscated].com/api/v1/packs/install
# -------- begin 139888917284112 response ----------
{
    "execution_id": "59af2a18bd00ef17f566e3a8"
}
# -------- end 139888917284112 response ------------


        [  running  ] download pack

ERROR: 'LiveAction' object has no attribute 'id'

CLI settings:
----------------
Config file path: /export/home/[obfuscated]/.st2/config
Client settings:
----------------
ST2_BASE_URL: https://lvcops101.[obfuscated].com
ST2_AUTH_URL: https://lvcops101.[obfuscated].com/auth/
ST2_API_URL: https://lvcops101.[obfuscated].com/api/v1
ST2_STREAM_URL: https://lvcops101.[obfuscated].com/api/v1
ST2_AUTH_TOKEN: b90f9cefc79540bf9c9c6f9cb1d6743a

Proxy settings:
---------------
HTTP_PROXY:
HTTPS_PROXY:

Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/shell.py", line 307, in run
    args.func(args)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/commands/resource.py", line 44, in decorate
    return func(*args, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/commands/pack.py", line 238, in run_and_print
    instance = super(PackInstallCommand, self).run_and_print(args, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/commands/resource.py", line 44, in decorate
    return func(*args, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/commands/pack.py", line 121, in run_and_print
    if execution.id == parent_id \
AttributeError: 'LiveAction' object has no attribute 'id'
```

**Comment by LindsayHill** [comment]
Just as a further data point, I saw something similar on a system I upgrade from 2.1 to 2.4.1. So it’s not just you

**Comment by LindsayHill** [comment]
I haven't seen any reports of similar things with recent versions. Let's close this one for now
